#if !canImport(ObjectiveC)
import XCTest

extension DateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DateTests = [
        ("testDateInit", testDateInit),
        ("testYMDInit", testYMDInit),
        ("testYMInit", testYMInit),
    ]
}

extension FoundationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FoundationTests = [
        ("testCurrent", testCurrent),
    ]
}

extension MonthTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MonthTests = [
        ("testCodable", testCodable),
        ("testInit", testInit),
    ]
}

extension SwiftYMDTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftYMDTests = [
        ("testExample", testExample),
    ]
}

extension YMDTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__YMDTests = [
        ("testComparable", testComparable),
        ("testDayOfWeek", testDayOfWeek),
        ("testDescription", testDescription),
        ("testInit", testInit),
        ("testOperators", testOperators),
        ("testRanges", testRanges),
    ]
}

extension YMTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__YMTests = [
        ("testComparable", testComparable),
        ("testDescription", testDescription),
        ("testInit", testInit),
        ("testNumberOfDays", testNumberOfDays),
        ("testOperators", testOperators),
        ("testRanges", testRanges),
    ]
}

extension YearTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__YearTests = [
        ("testCodable", testCodable),
        ("testIsLeapYear", testIsLeapYear),
        ("testNumberOfDays", testNumberOfDays),
        ("testOperators", testOperators),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DateTests.__allTests__DateTests),
        testCase(FoundationTests.__allTests__FoundationTests),
        testCase(MonthTests.__allTests__MonthTests),
        testCase(SwiftYMDTests.__allTests__SwiftYMDTests),
        testCase(YMDTests.__allTests__YMDTests),
        testCase(YMTests.__allTests__YMTests),
        testCase(YearTests.__allTests__YearTests),
    ]
}
#endif
